name: Go Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: |
          GOOS=$(echo ${{ matrix.os }} | sed 's/-latest//' | sed 's/ubuntu/linux/') GOARCH=amd64 go build -o output/myapp-${{ matrix.os }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp-${{ matrix.os }}
          path: output/myapp-${{ matrix.os }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts (Ubuntu)
        uses: actions/download-artifact@v2
        with:
          name: myapp-ubuntu-latest
          path: ./artifacts
        continue-on-error: true

      - name: Download artifacts (Windows)
        uses: actions/download-artifact@v2
        with:
          name: myapp-windows-latest
          path: ./artifacts
        continue-on-error: true

      - name: Download artifacts (macOS)
        uses: actions/download-artifact@v2
        with:
          name: myapp-macos-latest
          path: ./artifacts
        continue-on-error: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
